import type { ApiEnvelope, ModelPageView } from '@/types/api'

function envelope<T>(data: T): ApiEnvelope<T> {
  return {
    data,
    meta: {
      generated_at: new Date().toISOString(),
    },
  }
}

export async function listModels(): Promise<ApiEnvelope<ModelPageView>> {
  return envelope({
    items: [
      {
        id: 'fast',
        resolved_model_key: 'fast',
        alias_of: null,
        description: 'Gemini via OpenRouter',
        provider_key: 'openrouter',
        provider_label: 'OpenRouter',
        provider_icon_key: 'openrouter',
        upstream_model: 'google/gemini-2.0-flash',
        model_icon_key: 'gemini',
        input_cost_per_million_tokens_usd_10000: 3_000,
        output_cost_per_million_tokens_usd_10000: 25_000,
        cache_read_cost_per_million_tokens_usd_10000: null,
        context_window_tokens: 1_048_576,
        input_window_tokens: null,
        output_window_tokens: 65_536,
        supports_streaming: true,
        supports_vision: true,
        supports_tool_calling: true,
        supports_structured_output: true,
        supports_attachments: true,
        benchmark_scores: [
          {
            metric_key: 'artificial_analysis_intelligence_index',
            label: 'Artificial Analysis Intelligence Index',
            value: 39,
            unit: 'index_points',
            benchmark_version: '4.3',
            source: 'artificial_analysis',
            source_model_id: '36f73aaf-d38a-4b56-a2b3-d04d17186910',
            source_url: 'https://artificialanalysis.ai/models/gemini-2-0-flash',
            fetched_at: '2026-09-21T10:00:00Z',
          },
        ],
        tags: ['fast', 'cheap'],
        allowlist: null,
        status: 'healthy',
        client_configurations: [],
      },
      {
        id: 'reasoning',
        resolved_model_key: 'reasoning',
        alias_of: null,
        description: 'OpenAI reasoning tier',
        provider_key: 'openai-prod',
        provider_label: 'OpenAI',
        provider_icon_key: 'openai',
        upstream_model: 'o3-mini',
        model_icon_key: 'openai',
        input_cost_per_million_tokens_usd_10000: 12_500,
        output_cost_per_million_tokens_usd_10000: 100_000,
        cache_read_cost_per_million_tokens_usd_10000: null,
        context_window_tokens: 400_000,
        input_window_tokens: 272_000,
        output_window_tokens: 128_000,
        supports_streaming: true,
        supports_vision: true,
        supports_tool_calling: true,
        supports_structured_output: true,
        supports_attachments: true,
        benchmark_scores: [],
        tags: ['reasoning'],
        allowlist: {
          users: ['alice@example.com', 'bob@example.com'],
          teams: ['platform'],
        },
        status: 'healthy',
        client_configurations: [],
      },
      {
        id: 'backup-fast',
        resolved_model_key: 'backup-fast',
        alias_of: 'fast',
        description: 'Gemini fallback on Vertex',
        provider_key: 'vertex-gemini',
        provider_label: 'Google Vertex AI',
        provider_icon_key: 'vertexai',
        upstream_model: 'google/gemini-2.0-flash',
        model_icon_key: 'gemini',
        input_cost_per_million_tokens_usd_10000: 3_000,
        output_cost_per_million_tokens_usd_10000: 25_000,
        cache_read_cost_per_million_tokens_usd_10000: null,
        context_window_tokens: 1_048_576,
        input_window_tokens: null,
        output_window_tokens: 65_536,
        supports_streaming: true,
        supports_vision: true,
        supports_tool_calling: false,
        supports_structured_output: true,
        supports_attachments: true,
        benchmark_scores: [],
        tags: ['fast', 'fallback'],
        allowlist: {
          users: [],
          teams: ['research'],
        },
        status: 'degraded',
        client_configurations: [],
      },
    ],
    page: 1,
    page_size: 3,
    total: 3,
  })
}
