{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "oceans-llm.gatewayServiceName" . }}
  labels:
    {{- include "oceans-llm.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | quote }}
            backend:
              service:
                name: {{ include "oceans-llm.gatewayServiceName" $ }}
                port:
                  number: {{ $.Values.service.gateway.port }}
          {{- end }}
    {{- end }}
{{- end }}
