{{- if .Values.secrets.inline }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oceans-llm.inlineSecretName" . }}
  labels:
    {{- include "oceans-llm.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.inline }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
