StylesPath = styles
Vocab = Oceans
MinAlertLevel = warning
IgnoredScopes = code, tt, kbd, a

Packages = Google, Harper, AiTells, proselint, write-good

[*.{md,mdx}]
BasedOnStyles = Vale, Google, Harper, AiTells, Oceans, proselint, write-good, personal-readability
Google.Headings = NO
Microsoft.Headings = NO
Vale.Spelling = NO 
Microsoft.GeneralURL = NO
Google.WordListCase = NO
Google.WordList = NO
Harper.NumericRangeEnDash = NO

# Duplicated Rules
AiTells.Passive = NO
Google.Passive = NO
write-good.Passive = NO
write-good.TooWordy = NO
