[package]
name = "gateway-store"
version = "0.37.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
aws-config.workspace = true
aws-credential-types.workspace = true
aws-sdk-s3.workspace = true
gateway-core.workspace = true
libsql.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
agent-session-analysis.workspace = true
axum.workspace = true
futures-util.workspace = true
tempfile = "3"
serial_test = "4"
