/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpendControlsRouteImport } from './routes/spend-controls'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as AccountReadyRouteImport } from './routes/account-ready'
import { Route as IndexRouteImport } from './routes/index'
import { Route as McpIndexRouteImport } from './routes/mcp/index'
import { Route as ObservabilityUsageCostsRouteImport } from './routes/observability/usage-costs'
import { Route as ObservabilityRequestLogsRouteImport } from './routes/observability/request-logs'
import { Route as ObservabilityMcpInvocationsRouteImport } from './routes/observability/mcp-invocations'
import { Route as ObservabilityLeaderboardRouteImport } from './routes/observability/leaderboard'
import { Route as ObservabilityAgentHarnessesRouteImport } from './routes/observability/agent-harnesses'
import { Route as McpServersRouteImport } from './routes/mcp/servers'
import { Route as McpAccessRouteImport } from './routes/mcp/access'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as IdentityUsersRouteImport } from './routes/identity/users'
import { Route as IdentityTeamsRouteImport } from './routes/identity/teams'

const SpendControlsRoute = SpendControlsRouteImport.update({
  id: '/spend-controls',
  path: '/spend-controls',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountReadyRoute = AccountReadyRouteImport.update({
  id: '/account-ready',
  path: '/account-ready',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpIndexRoute = McpIndexRouteImport.update({
  id: '/mcp/',
  path: '/mcp/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityUsageCostsRoute = ObservabilityUsageCostsRouteImport.update({
  id: '/observability/usage-costs',
  path: '/observability/usage-costs',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRequestLogsRoute =
  ObservabilityRequestLogsRouteImport.update({
    id: '/observability/request-logs',
    path: '/observability/request-logs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ObservabilityMcpInvocationsRoute =
  ObservabilityMcpInvocationsRouteImport.update({
    id: '/observability/mcp-invocations',
    path: '/observability/mcp-invocations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ObservabilityLeaderboardRoute =
  ObservabilityLeaderboardRouteImport.update({
    id: '/observability/leaderboard',
    path: '/observability/leaderboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ObservabilityAgentHarnessesRoute =
  ObservabilityAgentHarnessesRouteImport.update({
    id: '/observability/agent-harnesses',
    path: '/observability/agent-harnesses',
    getParentRoute: () => rootRouteImport,
  } as any)
const McpServersRoute = McpServersRouteImport.update({
  id: '/mcp/servers',
  path: '/mcp/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const McpAccessRoute = McpAccessRouteImport.update({
  id: '/mcp/access',
  path: '/mcp/access',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityUsersRoute = IdentityUsersRouteImport.update({
  id: '/identity/users',
  path: '/identity/users',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityTeamsRoute = IdentityTeamsRouteImport.update({
  id: '/identity/teams',
  path: '/identity/teams',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-ready': typeof AccountReadyRoute
  '/api-keys': typeof ApiKeysRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/spend-controls': typeof SpendControlsRoute
  '/identity/teams': typeof IdentityTeamsRoute
  '/identity/users': typeof IdentityUsersRoute
  '/invite/$token': typeof InviteTokenRoute
  '/mcp/access': typeof McpAccessRoute
  '/mcp/servers': typeof McpServersRoute
  '/observability/agent-harnesses': typeof ObservabilityAgentHarnessesRoute
  '/observability/leaderboard': typeof ObservabilityLeaderboardRoute
  '/observability/mcp-invocations': typeof ObservabilityMcpInvocationsRoute
  '/observability/request-logs': typeof ObservabilityRequestLogsRoute
  '/observability/usage-costs': typeof ObservabilityUsageCostsRoute
  '/mcp/': typeof McpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-ready': typeof AccountReadyRoute
  '/api-keys': typeof ApiKeysRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/spend-controls': typeof SpendControlsRoute
  '/identity/teams': typeof IdentityTeamsRoute
  '/identity/users': typeof IdentityUsersRoute
  '/invite/$token': typeof InviteTokenRoute
  '/mcp/access': typeof McpAccessRoute
  '/mcp/servers': typeof McpServersRoute
  '/observability/agent-harnesses': typeof ObservabilityAgentHarnessesRoute
  '/observability/leaderboard': typeof ObservabilityLeaderboardRoute
  '/observability/mcp-invocations': typeof ObservabilityMcpInvocationsRoute
  '/observability/request-logs': typeof ObservabilityRequestLogsRoute
  '/observability/usage-costs': typeof ObservabilityUsageCostsRoute
  '/mcp': typeof McpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-ready': typeof AccountReadyRoute
  '/api-keys': typeof ApiKeysRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/spend-controls': typeof SpendControlsRoute
  '/identity/teams': typeof IdentityTeamsRoute
  '/identity/users': typeof IdentityUsersRoute
  '/invite/$token': typeof InviteTokenRoute
  '/mcp/access': typeof McpAccessRoute
  '/mcp/servers': typeof McpServersRoute
  '/observability/agent-harnesses': typeof ObservabilityAgentHarnessesRoute
  '/observability/leaderboard': typeof ObservabilityLeaderboardRoute
  '/observability/mcp-invocations': typeof ObservabilityMcpInvocationsRoute
  '/observability/request-logs': typeof ObservabilityRequestLogsRoute
  '/observability/usage-costs': typeof ObservabilityUsageCostsRoute
  '/mcp/': typeof McpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-ready'
    | '/api-keys'
    | '/change-password'
    | '/login'
    | '/models'
    | '/spend-controls'
    | '/identity/teams'
    | '/identity/users'
    | '/invite/$token'
    | '/mcp/access'
    | '/mcp/servers'
    | '/observability/agent-harnesses'
    | '/observability/leaderboard'
    | '/observability/mcp-invocations'
    | '/observability/request-logs'
    | '/observability/usage-costs'
    | '/mcp/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-ready'
    | '/api-keys'
    | '/change-password'
    | '/login'
    | '/models'
    | '/spend-controls'
    | '/identity/teams'
    | '/identity/users'
    | '/invite/$token'
    | '/mcp/access'
    | '/mcp/servers'
    | '/observability/agent-harnesses'
    | '/observability/leaderboard'
    | '/observability/mcp-invocations'
    | '/observability/request-logs'
    | '/observability/usage-costs'
    | '/mcp'
  id:
    | '__root__'
    | '/'
    | '/account-ready'
    | '/api-keys'
    | '/change-password'
    | '/login'
    | '/models'
    | '/spend-controls'
    | '/identity/teams'
    | '/identity/users'
    | '/invite/$token'
    | '/mcp/access'
    | '/mcp/servers'
    | '/observability/agent-harnesses'
    | '/observability/leaderboard'
    | '/observability/mcp-invocations'
    | '/observability/request-logs'
    | '/observability/usage-costs'
    | '/mcp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountReadyRoute: typeof AccountReadyRoute
  ApiKeysRoute: typeof ApiKeysRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  ModelsRoute: typeof ModelsRoute
  SpendControlsRoute: typeof SpendControlsRoute
  IdentityTeamsRoute: typeof IdentityTeamsRoute
  IdentityUsersRoute: typeof IdentityUsersRoute
  InviteTokenRoute: typeof InviteTokenRoute
  McpAccessRoute: typeof McpAccessRoute
  McpServersRoute: typeof McpServersRoute
  ObservabilityAgentHarnessesRoute: typeof ObservabilityAgentHarnessesRoute
  ObservabilityLeaderboardRoute: typeof ObservabilityLeaderboardRoute
  ObservabilityMcpInvocationsRoute: typeof ObservabilityMcpInvocationsRoute
  ObservabilityRequestLogsRoute: typeof ObservabilityRequestLogsRoute
  ObservabilityUsageCostsRoute: typeof ObservabilityUsageCostsRoute
  McpIndexRoute: typeof McpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spend-controls': {
      id: '/spend-controls'
      path: '/spend-controls'
      fullPath: '/spend-controls'
      preLoaderRoute: typeof SpendControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-ready': {
      id: '/account-ready'
      path: '/account-ready'
      fullPath: '/account-ready'
      preLoaderRoute: typeof AccountReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/': {
      id: '/mcp/'
      path: '/mcp'
      fullPath: '/mcp/'
      preLoaderRoute: typeof McpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability/usage-costs': {
      id: '/observability/usage-costs'
      path: '/observability/usage-costs'
      fullPath: '/observability/usage-costs'
      preLoaderRoute: typeof ObservabilityUsageCostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability/request-logs': {
      id: '/observability/request-logs'
      path: '/observability/request-logs'
      fullPath: '/observability/request-logs'
      preLoaderRoute: typeof ObservabilityRequestLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability/mcp-invocations': {
      id: '/observability/mcp-invocations'
      path: '/observability/mcp-invocations'
      fullPath: '/observability/mcp-invocations'
      preLoaderRoute: typeof ObservabilityMcpInvocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability/leaderboard': {
      id: '/observability/leaderboard'
      path: '/observability/leaderboard'
      fullPath: '/observability/leaderboard'
      preLoaderRoute: typeof ObservabilityLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability/agent-harnesses': {
      id: '/observability/agent-harnesses'
      path: '/observability/agent-harnesses'
      fullPath: '/observability/agent-harnesses'
      preLoaderRoute: typeof ObservabilityAgentHarnessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/servers': {
      id: '/mcp/servers'
      path: '/mcp/servers'
      fullPath: '/mcp/servers'
      preLoaderRoute: typeof McpServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/access': {
      id: '/mcp/access'
      path: '/mcp/access'
      fullPath: '/mcp/access'
      preLoaderRoute: typeof McpAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity/users': {
      id: '/identity/users'
      path: '/identity/users'
      fullPath: '/identity/users'
      preLoaderRoute: typeof IdentityUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity/teams': {
      id: '/identity/teams'
      path: '/identity/teams'
      fullPath: '/identity/teams'
      preLoaderRoute: typeof IdentityTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountReadyRoute: AccountReadyRoute,
  ApiKeysRoute: ApiKeysRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  ModelsRoute: ModelsRoute,
  SpendControlsRoute: SpendControlsRoute,
  IdentityTeamsRoute: IdentityTeamsRoute,
  IdentityUsersRoute: IdentityUsersRoute,
  InviteTokenRoute: InviteTokenRoute,
  McpAccessRoute: McpAccessRoute,
  McpServersRoute: McpServersRoute,
  ObservabilityAgentHarnessesRoute: ObservabilityAgentHarnessesRoute,
  ObservabilityLeaderboardRoute: ObservabilityLeaderboardRoute,
  ObservabilityMcpInvocationsRoute: ObservabilityMcpInvocationsRoute,
  ObservabilityRequestLogsRoute: ObservabilityRequestLogsRoute,
  ObservabilityUsageCostsRoute: ObservabilityUsageCostsRoute,
  McpIndexRoute: McpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
