/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ObservabilityUsageCostsRouteImport } from './routes/observability/usage-costs'
import { Route as ObservabilityRequestLogsRouteImport } from './routes/observability/request-logs'
import { Route as IdentityUsersRouteImport } from './routes/identity/users'
import { Route as IdentityTeamsRouteImport } from './routes/identity/teams'

const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityUsageCostsRoute = ObservabilityUsageCostsRouteImport.update({
  id: '/observability/usage-costs',
  path: '/observability/usage-costs',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRequestLogsRoute =
  ObservabilityRequestLogsRouteImport.update({
    id: '/observability/request-logs',
    path: '/observability/request-logs',
    getParentRoute: () => rootRouteImport,
  } as any)
const IdentityUsersRoute = IdentityUsersRouteImport.update({
  id: '/identity/users',
  path: '/identity/users',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityTeamsRoute = IdentityTeamsRouteImport.update({
  id: '/identity/teams',
  path: '/identity/teams',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/models': typeof ModelsRoute
  '/identity/teams': typeof IdentityTeamsRoute
  '/identity/users': typeof IdentityUsersRoute
  '/observability/request-logs': typeof ObservabilityRequestLogsRoute
  '/observability/usage-costs': typeof ObservabilityUsageCostsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/models': typeof ModelsRoute
  '/identity/teams': typeof IdentityTeamsRoute
  '/identity/users': typeof IdentityUsersRoute
  '/observability/request-logs': typeof ObservabilityRequestLogsRoute
  '/observability/usage-costs': typeof ObservabilityUsageCostsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/models': typeof ModelsRoute
  '/identity/teams': typeof IdentityTeamsRoute
  '/identity/users': typeof IdentityUsersRoute
  '/observability/request-logs': typeof ObservabilityRequestLogsRoute
  '/observability/usage-costs': typeof ObservabilityUsageCostsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/models'
    | '/identity/teams'
    | '/identity/users'
    | '/observability/request-logs'
    | '/observability/usage-costs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-keys'
    | '/models'
    | '/identity/teams'
    | '/identity/users'
    | '/observability/request-logs'
    | '/observability/usage-costs'
  id:
    | '__root__'
    | '/'
    | '/api-keys'
    | '/models'
    | '/identity/teams'
    | '/identity/users'
    | '/observability/request-logs'
    | '/observability/usage-costs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiKeysRoute: typeof ApiKeysRoute
  ModelsRoute: typeof ModelsRoute
  IdentityTeamsRoute: typeof IdentityTeamsRoute
  IdentityUsersRoute: typeof IdentityUsersRoute
  ObservabilityRequestLogsRoute: typeof ObservabilityRequestLogsRoute
  ObservabilityUsageCostsRoute: typeof ObservabilityUsageCostsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability/usage-costs': {
      id: '/observability/usage-costs'
      path: '/observability/usage-costs'
      fullPath: '/observability/usage-costs'
      preLoaderRoute: typeof ObservabilityUsageCostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability/request-logs': {
      id: '/observability/request-logs'
      path: '/observability/request-logs'
      fullPath: '/observability/request-logs'
      preLoaderRoute: typeof ObservabilityRequestLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity/users': {
      id: '/identity/users'
      path: '/identity/users'
      fullPath: '/identity/users'
      preLoaderRoute: typeof IdentityUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity/teams': {
      id: '/identity/teams'
      path: '/identity/teams'
      fullPath: '/identity/teams'
      preLoaderRoute: typeof IdentityTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiKeysRoute: ApiKeysRoute,
  ModelsRoute: ModelsRoute,
  IdentityTeamsRoute: IdentityTeamsRoute,
  IdentityUsersRoute: IdentityUsersRoute,
  ObservabilityRequestLogsRoute: ObservabilityRequestLogsRoute,
  ObservabilityUsageCostsRoute: ObservabilityUsageCostsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
