use gateway_core::InferredObservationKind;
use serde_json::{Value, json};

use super::{LocalDemoRequestFixture, local_demo_request_fixtures};

#[derive(Clone, Copy)]
pub(super) struct DemoAgentSessionFixture {
    pub key: &'static str,
    pub normalized_session_id: &'static str,
    pub tool_description: &'static str,
    pub request_count: usize,
    #[cfg(test)]
    pub expected_file_tool_calls: usize,
}

#[derive(Clone, Copy)]
pub(super) struct DemoAgentSessionRequest {
    pub session: &'static DemoAgentSessionFixture,
    pub step: usize,
    pub tool_name: &'static str,
    pub observation_kind: InferredObservationKind,
}

const GREENHOUSE_SESSION: DemoAgentSessionFixture = DemoAgentSessionFixture {
    key: "greenhouse-irrigation-reconciliation",
    normalized_session_id: "demo-greenhouse-irrigation-2026-07",
    tool_description: "Inspect the fictional greenhouse operations dataset.",
    request_count: 5,
    #[cfg(test)]
    expected_file_tool_calls: 0,
};

const ROUTE_MIGRATION_SESSION: DemoAgentSessionFixture = DemoAgentSessionFixture {
    key: "repository-route-migration",
    normalized_session_id: "demo-repository-route-migration-2026-07",
    tool_description: "Inspect or update the fictional repository migration workspace.",
    request_count: 9,
    #[cfg(test)]
    expected_file_tool_calls: 7,
};

#[cfg(test)]
pub(super) const DEMO_AGENT_SESSIONS: &[DemoAgentSessionFixture] =
    &[GREENHOUSE_SESSION, ROUTE_MIGRATION_SESSION];

pub(super) const ADDITIONAL_SESSION_REQUESTS: &[LocalDemoRequestFixture] = &[
    LocalDemoRequestFixture {
        request_id: "demo-agent-files-001",
        api_key_public_id: "locdemogina1",
        days_ago: 0,
        hours_ago: 1,
        minutes_ago: 56,
        model_key: "gpt-oss-120b",
        resolved_model_key: "gpt-oss-120b",
        provider_key: "bedrock-us-east-1",
        upstream_model: "gpt-oss-120b",
        prompt_tokens: Some(1_120),
        completion_tokens: Some(210),
        cost_scaled: 2_140,
        status_code: 200,
        latency_ms: 520,
        service: "developer-productivity",
        component: "repo-maintenance",
        env: "local",
        bespoke_key: "workflow",
        bespoke_value: "route-migration",
        prompt: "Inventory the fictional repository files involved in the observability route migration.",
        completion: "The inventory identified the route, navigation, authorization, test, and documentation surfaces.",
        error_code: None,
        payload_profile: super::DemoPayloadProfile::Standard,
    },
    LocalDemoRequestFixture {
        request_id: "demo-agent-files-002",
        api_key_public_id: "locdemogina1",
        days_ago: 0,
        hours_ago: 1,
        minutes_ago: 50,
        model_key: "gpt-oss-120b",
        resolved_model_key: "gpt-oss-120b",
        provider_key: "bedrock-us-east-1",
        upstream_model: "gpt-oss-120b",
        prompt_tokens: Some(1_540),
        completion_tokens: Some(250),
        cost_scaled: 2_760,
        status_code: 200,
        latency_ms: 610,
        service: "developer-productivity",
        component: "repo-maintenance",
        env: "local",
        bespoke_key: "workflow",
        bespoke_value: "route-migration",
        prompt: "Read the fictional workspace manifest and confirm the route generator inputs.",
        completion: "The manifest confirms file-based routing and the generated route tree contract.",
        error_code: None,
        payload_profile: super::DemoPayloadProfile::Standard,
    },
    LocalDemoRequestFixture {
        request_id: "demo-agent-files-003",
        api_key_public_id: "locdemogina1",
        days_ago: 0,
        hours_ago: 1,
        minutes_ago: 44,
        model_key: "gpt-oss-120b",
        resolved_model_key: "gpt-oss-120b",
        provider_key: "bedrock-us-east-1",
        upstream_model: "gpt-oss-120b",
        prompt_tokens: Some(1_980),
        completion_tokens: Some(280),
        cost_scaled: 3_340,
        status_code: 200,
        latency_ms: 690,
        service: "developer-productivity",
        component: "repo-maintenance",
        env: "local",
        bespoke_key: "workflow",
        bespoke_value: "route-migration",
        prompt: "Read the existing observability route before proposing the naming migration.",
        completion: "The route couples URL search, server pagination, filters, and a diagnostic sheet.",
        error_code: None,
        payload_profile: super::DemoPayloadProfile::Standard,
    },
    LocalDemoRequestFixture {
        request_id: "demo-agent-files-004",
        api_key_public_id: "locdemogina1",
        days_ago: 0,
        hours_ago: 1,
        minutes_ago: 38,
        model_key: "gpt-oss-120b",
        resolved_model_key: "gpt-oss-120b",
        provider_key: "bedrock-us-east-1",
        upstream_model: "gpt-oss-120b",
        prompt_tokens: Some(2_430),
        completion_tokens: Some(320),
        cost_scaled: 4_020,
        status_code: 200,
        latency_ms: 740,
        service: "developer-productivity",
        component: "repo-maintenance",
        env: "local",
        bespoke_key: "workflow",
        bespoke_value: "route-migration",
        prompt: "Search for every fictional navigation and test reference to the old route name.",
        completion: "The search found references in navigation, authorization, route tests, E2E coverage, and docs.",
        error_code: None,
        payload_profile: super::DemoPayloadProfile::Standard,
    },
    LocalDemoRequestFixture {
        request_id: "demo-agent-files-005",
        api_key_public_id: "locdemogina1",
        days_ago: 0,
        hours_ago: 1,
        minutes_ago: 32,
        model_key: "gpt-oss-120b",
        resolved_model_key: "gpt-oss-120b",
        provider_key: "bedrock-us-east-1",
        upstream_model: "gpt-oss-120b",
        prompt_tokens: Some(2_940),
        completion_tokens: Some(350),
        cost_scaled: 4_760,
        status_code: 200,
        latency_ms: 830,
        service: "developer-productivity",
        component: "repo-maintenance",
        env: "local",
        bespoke_key: "workflow",
        bespoke_value: "route-migration",
        prompt: "Write a bounded migration plan for the fictional route rename and generated files.",
        completion: "The plan sequences the source rename, callers, generated route tree, tests, and documentation.",
        error_code: None,
        payload_profile: super::DemoPayloadProfile::Standard,
    },
    LocalDemoRequestFixture {
        request_id: "demo-agent-files-006",
        api_key_public_id: "locdemogina1",
        days_ago: 0,
        hours_ago: 1,
        minutes_ago: 26,
        model_key: "gpt-oss-120b",
        resolved_model_key: "gpt-oss-120b",
        provider_key: "bedrock-us-east-1",
        upstream_model: "gpt-oss-120b",
        prompt_tokens: Some(3_420),
        completion_tokens: Some(390),
        cost_scaled: 5_480,
        status_code: 200,
        latency_ms: 910,
        service: "developer-productivity",
        component: "repo-maintenance",
        env: "local",
        bespoke_key: "workflow",
        bespoke_value: "route-migration",
        prompt: "Read the fictional route test failures after the mechanical rename.",
        completion: "The failures isolate stale heading, navigation target, and detail-sheet expectations.",
        error_code: None,
        payload_profile: super::DemoPayloadProfile::Standard,
    },
    LocalDemoRequestFixture {
        request_id: "demo-agent-files-007",
        api_key_public_id: "locdemogina1",
        days_ago: 0,
        hours_ago: 1,
        minutes_ago: 20,
        model_key: "gpt-oss-120b",
        resolved_model_key: "gpt-oss-120b",
        provider_key: "bedrock-us-east-1",
        upstream_model: "gpt-oss-120b",
        prompt_tokens: Some(3_880),
        completion_tokens: Some(420),
        cost_scaled: 6_120,
        status_code: 200,
        latency_ms: 980,
        service: "developer-productivity",
        component: "repo-maintenance",
        env: "local",
        bespoke_key: "workflow",
        bespoke_value: "route-migration",
        prompt: "Edit the fictional route configuration to use the new session-oriented path.",
        completion: "The route, navigation target, and capability gate now share the session path.",
        error_code: None,
        payload_profile: super::DemoPayloadProfile::Standard,
    },
    LocalDemoRequestFixture {
        request_id: "demo-agent-files-008",
        api_key_public_id: "locdemogina1",
        days_ago: 0,
        hours_ago: 1,
        minutes_ago: 14,
        model_key: "gpt-oss-120b",
        resolved_model_key: "gpt-oss-120b",
        provider_key: "bedrock-us-east-1",
        upstream_model: "gpt-oss-120b",
        prompt_tokens: Some(4_360),
        completion_tokens: Some(450),
        cost_scaled: 6_840,
        status_code: 200,
        latency_ms: 1_060,
        service: "developer-productivity",
        component: "repo-maintenance",
        env: "local",
        bespoke_key: "workflow",
        bespoke_value: "route-migration",
        prompt: "Read the generated fictional route diff and check for orphaned paths.",
        completion: "The generated tree contains only the session route and no orphaned task page path.",
        error_code: None,
        payload_profile: super::DemoPayloadProfile::Standard,
    },
    LocalDemoRequestFixture {
        request_id: "demo-agent-files-009",
        api_key_public_id: "locdemogina1",
        days_ago: 0,
        hours_ago: 1,
        minutes_ago: 8,
        model_key: "gpt-oss-120b",
        resolved_model_key: "gpt-oss-120b",
        provider_key: "bedrock-us-east-1",
        upstream_model: "gpt-oss-120b",
        prompt_tokens: Some(4_820),
        completion_tokens: Some(490),
        cost_scaled: 7_520,
        status_code: 200,
        latency_ms: 1_120,
        service: "developer-productivity",
        component: "repo-maintenance",
        env: "local",
        bespoke_key: "workflow",
        bespoke_value: "route-migration",
        prompt: "Write the fictional validation report with route, keyboard, and filter evidence.",
        completion: "The report records passing route tests, keyboard navigation, date filtering, and generated output.",
        error_code: None,
        payload_profile: super::DemoPayloadProfile::Streamed,
    },
];

pub(super) fn request_metadata(
    fixture: &LocalDemoRequestFixture,
) -> Option<DemoAgentSessionRequest> {
    let (session, step, tool_name, observation_kind) = match fixture.request_id {
        "demo-agent-session-001" => (
            &GREENHOUSE_SESSION,
            0,
            "inventory_telemetry_batches",
            InferredObservationKind::ToolCallClassified,
        ),
        "demo-agent-session-002" => (
            &GREENHOUSE_SESSION,
            1,
            "compare_valve_schedule",
            InferredObservationKind::ToolCallClassified,
        ),
        "demo-agent-session-003" => (
            &GREENHOUSE_SESSION,
            2,
            "trace_controller_retry",
            InferredObservationKind::ToolCallClassified,
        ),
        "demo-agent-session-004" => (
            &GREENHOUSE_SESSION,
            3,
            "validate_replay_guard",
            InferredObservationKind::ToolCallClassified,
        ),
        "demo-agent-session-005" => (
            &GREENHOUSE_SESSION,
            4,
            "save_repair_plan",
            InferredObservationKind::ToolCallClassified,
        ),
        "demo-agent-files-001" => (
            &ROUTE_MIGRATION_SESSION,
            0,
            "list_repository_files",
            InferredObservationKind::FileSearchSuspected,
        ),
        "demo-agent-files-002" => (
            &ROUTE_MIGRATION_SESSION,
            1,
            "read_workspace_manifest",
            InferredObservationKind::FileReadSuspected,
        ),
        "demo-agent-files-003" => (
            &ROUTE_MIGRATION_SESSION,
            2,
            "read_observability_route",
            InferredObservationKind::FileReadSuspected,
        ),
        "demo-agent-files-004" => (
            &ROUTE_MIGRATION_SESSION,
            3,
            "search_route_references",
            InferredObservationKind::FileSearchSuspected,
        ),
        "demo-agent-files-005" => (
            &ROUTE_MIGRATION_SESSION,
            4,
            "write_migration_plan",
            InferredObservationKind::FileCreateSuspected,
        ),
        "demo-agent-files-006" => (
            &ROUTE_MIGRATION_SESSION,
            5,
            "read_route_test_failures",
            InferredObservationKind::FileReadSuspected,
        ),
        "demo-agent-files-007" => (
            &ROUTE_MIGRATION_SESSION,
            6,
            "edit_route_configuration",
            InferredObservationKind::FileEditSuspected,
        ),
        "demo-agent-files-008" => (
            &ROUTE_MIGRATION_SESSION,
            7,
            "read_generated_route_diff",
            InferredObservationKind::FileReadSuspected,
        ),
        "demo-agent-files-009" => (
            &ROUTE_MIGRATION_SESSION,
            8,
            "write_validation_report",
            InferredObservationKind::FileCreateSuspected,
        ),
        _ => return None,
    };
    Some(DemoAgentSessionRequest {
        session,
        step,
        tool_name,
        observation_kind,
    })
}

pub(super) fn session_requests(
    session: &'static DemoAgentSessionFixture,
) -> impl Iterator<Item = &'static LocalDemoRequestFixture> {
    local_demo_request_fixtures().filter(move |fixture| {
        request_metadata(fixture).is_some_and(|request| request.session.key == session.key)
    })
}

pub(super) fn tool_arguments(request: DemoAgentSessionRequest) -> Value {
    if request.session.key == GREENHOUSE_SESSION.key {
        let sample = match request.step {
            0 => "batch-inventory",
            1 => "valve-schedule",
            2 => "controller-retry",
            3 => "seven-day-validation",
            _ => "repair-plan",
        };
        json!({"zone": "seven", "sample": sample})
    } else {
        let path = match request.step {
            0 => "crates/admin-ui/web/src/routes/observability",
            1 => "crates/admin-ui/web/package.json",
            2 => "crates/admin-ui/web/src/routes/observability/agent-tasks.tsx",
            3 => "crates/admin-ui/web/src",
            4 => "plans/route-migration.txt",
            5 => "crates/admin-ui/web/src/test/routes",
            6 => "crates/admin-ui/web/src/routes/observability/agent-sessions.tsx",
            7 => "crates/admin-ui/web/src/routeTree.gen.ts",
            _ => "reports/route-migration-validation.txt",
        };
        json!({"repository": "oceans-llm-demo", "path": path})
    }
}
